sudo: false
language: node_js
node_js:
  - '10'
  - '12'
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run init-db
  - npm run ci
after_script:
  - npminstall codecov && codecov
